language: python

python:
    - "2.6"
    - "2.7"

env:
    - DB=mysql DJANGO_VERSION=1.4
    - DB=mysql DJANGO_VERSION=1.5

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install build-essential python-dev python-pip python-virtualenv libxml2-dev libxslt-dev libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev zlib1g-dev sqlite3
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so /usr/lib
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so /usr/lib

install:
    - pip install --use-mirrors "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99"
    - pip install -r requirements/dev.txt --use-mirrors

script: python manage.py test -v2 badger

notifications:
    email:
        - me@lmorchard.com
    irc:
        channels:
            - "irc.mozilla.org#badger"
        on_success: always
        on_failure: always
